version: "3.9"
services:
  mysql:
    image: "mysql:8"
    environment:
      MYSQL_USER: seconds
      MYSQL_DATABASE: seconds
      MYSQL_ROOT_PASSWORD: seconds
      MYSQL_PASSWORD: seconds
    cap_add: [SYS_NICE]
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"
  redis:
    image: "redis:alpine"
    ports:
      - "127.0.0.1:6379:6379"
  minio:
    image: "minio/minio:RELEASE.2022-06-25T15-50-16Z"
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9001:9001"
    environment:
      MINIO_ROOT_USER: seconds
      MINIO_ROOT_PASSWORD: seconds123
      MINIO_ACCESS_PASSWORD: seconds123
    command:
      - "server"
      - "/data"
      - "--console-address"
      - ":9001"

  minio_init:
    image: "minio/mc:RELEASE.2022-06-26T18-51-48Z"
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 3;
      /usr/bin/mc alias set minio http://minio:9000 seconds seconds123;
      /usr/bin/mc mb minio/seconds;
      /usr/bin/mc policy set public minio/seconds;
      exit 0;
      "

volumes:
  mysql-data:
